### ISSUE TITLE
Not allowed to own the service "com.raspberrypi-bluetooth.Thermometer" due to security policies

### ISSUE THREAD

**Issue by wallem89** [markjlorenz/raspberry-pi-bluetooth-low-energy#2]
I am trying to run the docker image as given in the [readme ](https://www.raspberrypi-bluetooth.com/bluetooth-application-in-python.html) but I get an error regarding security policies of in ?the? configuration file.

Running it with ```sudo``` gives the same result.

Full error:
```
$ docker run -it --rm   --privileged   --workdir /app   --volume "$PWD":/app   --volume /var/run/dbus/:/var/run/dbus/:z soodesune/python3-bluetooth src/dbus_bluetooth.py
Traceback (most recent call last):
  File "src/dbus_bluetooth.py", line 56, in <module>
    bm = BluetoothManager()
  File "src/dbus_bluetooth.py", line 24, in __init__
    bus.register_service("com.raspberrypi-bluetooth.Thermometer")
  File "/usr/local/lib/python3.8/site-packages/dasbus/connection.py", line 259, in register_service
    result = self.proxy.RequestName(service_name, flags)
  File "/usr/local/lib/python3.8/site-packages/dasbus/client/handler.py", line 444, in _call_method
    return self._get_method_reply(
  File "/usr/local/lib/python3.8/site-packages/dasbus/client/handler.py", line 477, in _get_method_reply
    return self._handle_method_error(error)
  File "/usr/local/lib/python3.8/site-packages/dasbus/client/handler.py", line 497, in _handle_method_error
    raise exception from None
dasbus.error.DBusError: Connection ":1.63" is not allowed to own the service "com.raspberrypi-bluetooth.Thermometer" due to security policies in the configuration file
not allowed to own the service "com.raspberrypi-bluetooth.Thermometer" due to security policiesdocker run -it --rm   --privileged   --workdir /app   --volume "$PWD":/app   --volume /var/run/dbus/:/var/run/dbus/:z soodesune/python3-bluetooth src/dbus_bluetooth.py
```

When running the ```dbus_bluetooth.py``` when doing a local clone this repo I get the same error when running ```python3 src/dbus_bluetooth.py```.

**Comment by jacknudelman** [comment]
This stackoverflow was able to fix the issue for me: https://stackoverflow.com/questions/4560877/dbus-bus-request-name-connections-are-not-allowed-to-own-the-service
